services:
  - type: web
    name: edututor-kenya
    env: python
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade
    startCommand: gunicorn run:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: edututor-db
          property: connectionString
      - key: FLASK_ENV
        value: production

databases:
  - name: edututor-db
    plan: free
    databaseName: edututor
    user: edututor_user